### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by Cherkah** [aksel/dotfiles#1]
hi aksel.
 related to your post about spotify-vlc: https://github.com/jonas-lundqvist/vlc-spotify/issues/2
i would like to run the couple on my manjaro but i'm an and-user guy (no skills).
so:
did you got success to run spotify over vlc.
how did you do that?
 can you provides an HowTo on your github place?

sorry for this false issue on dotfiles repo, but i didn't find any personal address about you.
if you want to send personal email you can.
delete this issue as you want.

regards

**Comment by aksel** [comment]
Hi Cherkah, no worries about the issue.

GitHub really should add some private message support, because I, too, have found myself in your situation, and have posted off-topic issues on various repositories :smile: 

I didn't find a way to run Spotify over VLC, sadly.

I ended up using [spotifyd](https://github.com/Spotifyd/spotifyd). It is a lightweight daemon, which makes your computer act as a Spotify Connect device, like a PS4 or Chromecast.
